



const data = [
  {
    id: 1,
    title: "IngestAI",
    description:
      "A tool that helps people turn their knowledge base into a chatbot-like assistant. The tool is compatible with Slack, Discord, Whatsapp, Telegram, and more. It takes minutes to get started and supports uploading Knowledge-base files such as Markdown, TXT, Word, Excel, PowerPoint, Notion and Confluence. It will provide accurate AI/Chatbot-generated answers to questions about related materials. People can use it to help answer questions about their product, services, company knowledge base, and more.",
    image: require("./asset/IngestAI.webp"),
    plan: "Paid",
    category: ["Customer Support"],
    link: "https://ingestai.io",
    verified: true,
    price: 39,
    duration: "Month",
    instagram: null,
    facebook: null,
    linkedin: null,
    categoryid:1,
    categoryslug:'customer-support',
    slug:'ingestai',
  },
  {
    id: 2,
    title: "Fliki",
    description:
      "Create videos from scripts or blog posts using realistic voices in 2 minutes! Transform blog articles into videos. Lifelike Text to Speech Voices. Rich stock media library. Trusted by 30k+ content creators from companies like Google, Meta, Bytedance and Upwork.",
    image: require("./asset/Fliki.webp"),
    plan: "Freemium",
    category: ["Video Generator"],
    link: "https://fliki.ai",
    verified: true,
    price: 8,
    duration: "Month",
    instagram: 'https://www.instagram.com/fliki/',
    facebook: 'https://www.facebook.com/flikiai',
    linkedin: 'https://www.linkedin.com/company/fliki',
    categoryid:2,
    categoryslug:'video-generator',
    slug:'fliki'
  },
  {
    id: 3,
    title: "MarketingBlocks AI",
    description:
      "All-In-One AI Marketing Assistant that writes, creates & designs all your landing pages, promo videos, ads, marketing copy, graphics, email swipes, voiceovers, blog posts, articles, art & more in minutes.",
    image: require("./asset/MarketingBlocks.webp"),
    plan: "Freemium",
    category: ["Copywriting"],
    link: "https://fliki.ai",
    verified: true,
    price: 57,
    duration: "Month",
    instagram: null,
    facebook: null,
    linkedin: null,
    categoryid:3,
    categoryslug:'copywriting',
    slug:'marketingblock-ai',

  },
  {
    id: 4,
    title: "Stable Diffusion",
    description:"Stable Diffusion is a deep learning, text-to-image model released in 2022. It is primarily used to generate detailed images conditioned on text descriptions, though it can also be applied to other tasks such as inpainting, outpainting, and generating image-to-image translations guided by a text prompt.",
         image: require("./asset/Stable Diffusion.webp"),
    plan: "Freemium",
    category: ["Image Generator"],
    link: "https://stability.ai/",
    verified: true,
    price: null,
    duration: null,
    instagram: null,
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/stability-ai/mycompany/',
    categoryid:4,
    categoryslug:'image-generator',
    slug:'stable-diffusion',
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryid:3,
    categoryslug:'copywriting',
    slug:'adcreative-ai'
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting3"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryid:6,
    categoryslug:'copywriting3',
    slug:'adcreative-ai'
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting2"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryslug:'copywriting2',
    categoryid:7,
    slug:'adcreative-ai'
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting1"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryid:8,
    categoryslug:'copywriting1',
    slug:'adcreative-ai'
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting6"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryslug:'copywriting6',
    categoryid:10,
    slug:'adcreative-ai'
  },
  {
    id: 5,
    title: "Adcreative.ai",
    description:"Generate conversion focused ad and social media post creatives in a matter of seconds. Get better results while saving time.",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trail",
    category: ["Copywriting5"],
    link: "https://www.adcreative.ai/",
    verified: true,
    price: 29,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryslug:'copywriting5',
    slug:'adcreative-ai',
    categoryid:13,
  },
  {
    id: 6,
    title: "ChatGPT",
    description:"the best copywriting sdlnnlsdnsdnnnsdnlnsdjklsndjnjsdnjlorem",
             image: require("./asset/Adcreative.webp"),
    plan: "Free Trial",
    category: ["Copywriting"],
    link: "https://www.chatgpt.com/",
    verified: true,
    price: 15,
    currency:'Dollar',
    duration:"Month" ,
    instagram: 'https://www.instagram.com/adcreative.ai/',
    facebook: null,
    linkedin: 'https://www.linkedin.com/company/adcreative-ai/',
    categoryslug:'copywriting',
    slug:'chatgpt-ai',
    categoryid:3,
  },
];
export default data;
