

const data=[
{id:1,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",
date:'22 june 2023',
} ,   
{id:2,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",
date:'22 june 2023',
} ,   
{id:3,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",
date:'22 june 2023',
} ,   
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",
date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",
date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",


date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",

date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",

date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",

date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",

date:'22 june 2023',
},    
{id:4,
title:'Job listing platform Indeed lays off 2,200 employees',
description:'At a company that helps people find jobs, 2,200 employees will now have to embark on a job search of their own. Indeed laid off 15% of employees today, CEO Chris Hyams announced in an all-hands meeting. In a blog post, Hyams elaborated on the decision by expl…',
url: "https://techcrunch.com/2023/03/22/job-listing-platform-indeed-lays-off-2200-employees/",
image:"https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1244460682.jpg?resize=1200,799",

date:'22 june 2023',
},    
]
export default data;