const productivetool=[

        
        { id: 1, title: "Copy Writing", image:require('../asset/assetforbrowsepage/productivity.png') ,slug:'copywriting' },

        { id: 3, title: "Image Generator", image:require('../asset/assetforbrowsepage/imagegenerator.png') ,slug:'image-generator' },
        { id: 5, title: "Art", image:require('../asset/assetforbrowsepage/art.png') },
        // { id: 6, title: "Audio editing", image:require('../asset/assetforbrowsepage/audioediting.png') ,
        { id: 7, title: "Code assistant", image:require('../asset/assetforbrowsepage/coding.png') },
        { id: 7, title: "Customer support", image:require('../asset/assetforbrowsepage/customersupport.png'),slug:'customer-support' },
        // { id: 7, title: "Desgin Assistant", image:require('../asset/assetforbrowsepage/desginassistant.png') },
        { id: 7, title: "Developer Tools", image:require('../asset/assetforbrowsepage/developer.png') },
        // { id: 7, title: "E-commerce", image:require('../asset/assetforbrowsepage/ecommerce.png') },
        // { id: 7, title: "Education assistant", image:require('../asset/assetforbrowsepage/education.png') },
        { id: 7, title: "Email assistant", image:require('../asset/assetforbrowsepage/email.png') },
        // { id: 7, title: "Experiments", image:require('../asset/assetforbrowsepage/experiment.png') },
        // { id: 7, title: "Fashion", image:require('../asset/assetforbrowsepage/fashion.png') },
        { id: 7, title: "Finance", image:require('../asset/assetforbrowsepage/finance.png') },
        // { id: 7, title: "Fun tools", image:require('../asset/assetforbrowsepage/fun.png') },
        // { id: 7, title: "Gaming", image:require('../asset/assetforbrowsepage/game.png') },
        { id: 7, title: "General writing", image:require('../asset/assetforbrowsepage/writing.png') },
        // { id: 8, title: "Gift Ideas", image:require('../asset/assetforbrowsepage/gift.png') },
        // { id: 8, title: "Health Care", image:require('../asset/assetforbrowsepage/health.png') },
        // { id: 8, title: "Human resources", image:require('../asset/assetforbrowsepage/hr.png') },
        { id: 8, title: "Image editing", image:require('../asset/assetforbrowsepage/editimage.png') },
        { id: 8, title: "Legal assistant", image:require('../asset/assetforbrowsepage/legal.png') },
        // { id: 8, title: "Life assistant", image:require('../asset/assetforbrowsepage/life.png') },
        // { id: 8, title: "Logo generator", image:require('../asset/assetforbrowsepage/logo.png') },
        { id: 8, title: "Low-code/No-code", image:require('../asset/assetforbrowsepage/lowcode.png') },
        // { id: 8, title: "memory", image:require('../asset/assetforbrowsepage/memory.png') },
        // { id: 8, title: "Music", image:require('../asset/assetforbrowsepage/music.png') },
        { id: 8, title: "Presentations", image:require('../asset/assetforbrowsepage/presentation.png') },
        { id: 8, title: "Prompts", image:require('../asset/assetforbrowsepage/prompt.png') },
        // { id: 8, title: "Real estate", image:require('../asset/assetforbrowsepage/realstate.png') },
        { id: 8, title: "Research", image:require('../asset/assetforbrowsepage/research.png') },
        { id: 8, title: "Resource", image:require('../asset/assetforbrowsepage/resource.png') },
        // { id: 8, title: "Sales", image:require('../asset/assetforbrowsepage/sales.png') },
        // { id: 8, title: "SEO", image:require('../asset/assetforbrowsepage/seo.png') },
        // { id: 8, title: "Social Media", image:require('../asset/assetforbrowsepage/socialmedia.png') },
        // { id: 8, title: "Spreadsheets", image:require('../asset/assetforbrowsepage/spreadsheet.png') },
        // { id: 8, title: "SQL", image:require('../asset/assetforbrowsepage/sql.png') },
        { id: 8, title: "Start Up", image:require('../asset/assetforbrowsepage/startup.png') },
        { id: 8, title: "Text to speech", image:require('../asset/assetforbrowsepage/texttospeech.png') },
        { id: 8, title: "Transciption", image:require('../asset/assetforbrowsepage/transcrption.png') },
        // { id: 8, title: "Video Editing", image:require('../asset/assetforbrowsepage/videoeditor.png') ,slug:'video-generator'},
    
];
export default productivetool;